# Generated by Django 4.2.7 on 2024-03-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailings', '0002_remove_mailing_date_remove_mailing_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата следующей рассылки'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='period',
            field=models.CharField(choices=[('ежедневно', 'ежедневно'), ('еженедельно', 'еженедельно'), ('ежемесячно', 'ежемесячно')], default='еженедельно', max_length=30, verbose_name='Период'),
        ),
    ]
